apps/game/urls.py
from django.urls import path, include

from . import views

app_name = "game"

urlpatterns = [
    path(
        "word/",
        include(
            [
                path("list/", views.WordListView.as_view(), name="list"),
                path("create/", views.WordCreateView.as_view(), name="create"),
                path("room-create/", views.WordCreateView.as_view(), name="create"),
            ]
        ),
    ),
]

apps/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = "user"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("update_u/<int:pk>/", login_required(views.UserUpdateView.as_view()), name="update_u"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("game/", include("apps.game.urls")),
    path("", include("apps.game.urls_root")),
]

apps/game/models.py
from django.core.exceptions import ValidationError
from django.db import models


# Create your models here.
class Word(models.Model):
    word = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return f"{self.word}"

    __repr__ = __str__

    def clean(self):
        # Don't allow draft entries to have a pub_date.
        if not (self.word.isalpha()) or self.word is None:
            raise ValidationError('Enter right word!')
        if self.word.find("ь") != -1 or self.word.find("ъ") != -1 or self.word.find("ы") != -1:
            raise ValidationError('Enter right word without ь or ъ or ы!')
        last_word = Word.objects.order_by("-pk").first()
        if last_word is not None and last_word.word[-1] != self.word[0]:
            raise ValidationError(f'Enter word begin with "{last_word.word[-1]}"')


class Room(models.Model):
    room_number = models.SmallIntegerField(max_length=100, unique=True)
    main_player = models.CharField(max_length=100, unique=True)
    other_player = models.SmallIntegerField(max_length=100, unique=True)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    # pass
    avatar = models.ImageField(
        max_length=300,
        upload_to="contacts/contact/avatar/",
        blank=True,
        null=True,
        default=None,
    )

apps/game/views.py
from django.contrib.auth.models import AbstractUser
from django.contrib.sessions.backends.cached_db import SessionStore
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView

from apps.game.models import Word, Room


class WordListView(ListView):
    model = Word


def index(request):
    return render(
        request=request,
        template_name="index.html",
    )


class WordCreateView(CreateView):
    model = Word

    fields = (
        "word",
    )
    success_url = reverse_lazy("game:create")
    
    
class RoomCreate(TemplateView):
    model = Room
    
    fields = (
        "room_number",
        "main_player",
        "other_player",
    )

    def get_context_data(self, **kwargs):
        session: SessionStore = self.request.session

        context = super().get_context_data(**kwargs)
        context["session_id"] = session.session_key
        return context

apps/users/views.py
from django.shortcuts import redirect
from django.contrib.auth import get_user_model, login
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms


User = get_user_model()


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"class": "form-input"}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"class": "form-input"}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "form-input"}))
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput(attrs={"class": "form-input"}))

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "avatar",
        )


class SignUpView(CreateView):
    # form_class = UserCreationForm
    form_class = RegisterUserForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("root:index")


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = "registration/login.html"


class UserUpdateView(UpdateView):
    model = User

    template_name = "registration/edit.html"
    fields = (
        "username",
        "email",
        "password",
        "avatar",
    )
    success_url = reverse_lazy("root:index")

apps/templates/_helpers/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if title %}
            {{ title }} |
        {% endif %}
            My Django Apps
    </title>

    {# [connect_bootstrap] - [BEGIN] #}
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
    >
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"
    ></script>
    {# [connect_bootstrap] - [END] #}
    <link
            href="{% static 'styles/index.css' %}"
            rel="stylesheet"
    >
    <link rel="icon" type="image/svg+xml" href="{% static "./favicons/sun-one.svg" %}">
</head>
<body>
<h1>Game "Words"!</h1>
<div class="container-fluid">
    {% include "_helpers/_header.html" %}
    {% block content %}
        Hello!
    {% endblock %}
</div>
</body>
</html>

apps/templates/_helpers/_header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <ul class="navbar-nav">
            <div id="logo">
                <object
                    type="image/svg+xml"
                    data="/static/logo/logo.svg">
                    <img
                        src="/logo/logo.svg"
                        id="logo"
                        alt="">
                </object>
            </div>
        </ul>
    </nav>
</header>

apps/templates/game/room_create.html
{% extends "_helpers/_base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
    <a href="{% url "game:create" %}">
        <button type="button" class="btn btn-success">
            Add word
        </button>
    </a>


        <ul>
            {% for word in object_list %}
                <li>
                    <span>{{ word.word }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

apps/templates/game/word_form.html
{% extends "_helpers/_base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="post">
        {% csrf_token %}

            {{ form | crispy }}

        <button type="submit" class="btn btn-primary">Add word</button>
    </form>
    <a href="{% url "game:list" %}">
        <button type="button" class="btn btn-info">
            Back to list
        </button>
    </a>
    </div>
{% endblock %}

apps/templates/game/word_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'game:create' %}">
    <button>
        Create
    </button>
</a>
<ul>
    {% for word in object_list %}
        <li>
            <span>{{ word.word }}</span>
        </li>
    {% endfor %}
</ul>

</body>
</html>

apps/templates/index.html
{% extends "_helpers/_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <a href="{% url 'game:list' %}">
            <button type="submit" class="btn btn-primary">Start game</button>
        </a>
    <   a href="{% url 'game:crea' %}">
            <button type="submit" class="btn btn-primary">Start game</button>
        </a>
    </div>
{% endblock %}